#!/bin/bash

set -euxo pipefail

make -B DOCKER_LABEL=stable DOCKER_REPO=sirsedev/test-repo GRANDINE_VERSION=0.1.0 NETHERMIND_VERSION=1.38.0 nethermind-docker

docker rm $(docker stop nethermind-grandine)

# docker run -d --name nethermind-grandine --network grandine-net -v /disk/workspace/jwtsecret:/data/jwtsecret -v /disk/workspace/mainnet/grandine:/data/grandine -v /disk/workspace/mainnet/nethermind:/data/nethermind -p 5060:5060 -p 9054:9054 -p 9054:9054/udp -p 9056:9056 -p 9056:9056/udp -p 5061:5061 -p 8551:8551 -e GRANDINE_LOG=info,p2p=debug,eth2_libp2p=debug,builder_api=debug,fork_choice_control=debug,eth1_api=debug --pull=always sirsedev/test-repo:stable-nethermind --Grandine.Enabled true -c mainnet --Grandine.DataDir /data/grandine --Grandine.HttpPort 5060 --Grandine.HttpAddress 0.0.0.0 --Grandine.Libp2PPort 9054 --Grandine.DiscoveryPort 9054 --Grandine.QuicPort 9056 --Grandine.DisableUpnp true --Grandine.Metrics true --Grandine.MetricsPort 5061 --Grandine.MetricsAddress 0.0.0.0 --Grandine.CheckpointSyncUrl https://sync-mainnet.beaconcha.in --Grandine.Features LogBlockProcessingTime,LogHttpRequests,DebugP2pMessages,WarnOnStateCacheSlotProcessing,WarnOnFailedServiceHealthChecks --Grandine.MetricsUpdateInterval 1 --Grandine.TelemetryMetricsUrl http://tempo:4317 --Grandine.TelemetryServiceName embedded-grandine-hoodi --Grandine.TelemetryLevel debug --Grandine.BackSync true --init-logrules Grandine.NethermindPlugin.*:debug --datadir /data/nethermind --JsonRpc.EngineHost 0.0.0.0 --JsonRpc.EnginePort 8551 --JsonRpc.JwtSecretFile /data/jwtsecret

# docker run -d --name nethermind-grandine --network grandine-net -v /disk/workspace/jwtsecret:/data/jwtsecret -v /disk/workspace/mainnet/grandine:/data/grandine -v /disk/workspace/mainnet/nethermind:/data/nethermind -p 5060:5060 -p 9054:9054 -p 9054:9054/udp -p 9056:9056 -p 9056:9056/udp -p 5061:5061 -p 8551:8551 -e GRANDINE_LOG=info,p2p=debug,eth2_libp2p=debug,builder_api=debug,fork_choice_control=debug,eth1_api=debug --pull=always sifrai/grandine:unstable-nethermind --Grandine.Enabled true -c mainnet --Grandine.DataDir /data/grandine --Grandine.HttpPort 5060 --Grandine.HttpAddress 0.0.0.0 --Grandine.Libp2PPort 9054 --Grandine.DiscoveryPort 9054 --Grandine.QuicPort 9056 --Grandine.DisableUpnp true --Grandine.Metrics true --Grandine.MetricsPort 5061 --Grandine.MetricsAddress 0.0.0.0 --Grandine.CheckpointSyncUrl https://sync-mainnet.beaconcha.in --Grandine.Features LogBlockProcessingTime,LogHttpRequests,DebugP2pMessages,WarnOnStateCacheSlotProcessing,WarnOnFailedServiceHealthChecks --Grandine.MetricsUpdateInterval 1 --Grandine.TelemetryMetricsUrl http://tempo:4317 --Grandine.TelemetryServiceName embedded-grandine-hoodi --Grandine.TelemetryLevel debug --Grandine.BackSync true --init-logrules Grandine.NethermindPlugin.*:debug --datadir /data/nethermind --JsonRpc.EngineHost 0.0.0.0 --JsonRpc.EnginePort 8551 --JsonRpc.JwtSecretFile /data/jwtsecret

docker run -d --name nethermind-grandine --network grandine-net -v /disk/workspace/jwtsecret:/data/jwtsecret -v /disk/workspace/mainnet/grandine2:/data/grandine -v /disk/workspace/mainnet/nethermind:/data/nethermind -p 5060:5060 -p 9054:9054 -p 9054:9054/udp -p 9056:9056 -p 9056:9056/udp -p 5061:5061 -p 8551:8551 -e GRANDINE_LOG=info,p2p=debug,eth2_libp2p=debug,builder_api=debug,fork_choice_control=debug,eth1_api=debug --pull=always sirsedev/test-repo:stable-nethermind --Grandine.Enabled true -c mainnet --Grandine.DataDir /data/grandine --Grandine.HttpPort 5060 --Grandine.HttpAddress 0.0.0.0 --Grandine.Libp2PPort 9054 --Grandine.DiscoveryPort 9054 --Grandine.QuicPort 9056 --Grandine.DisableUpnp true --Grandine.Metrics true --Grandine.MetricsPort 5061 --Grandine.MetricsAddress 0.0.0.0 --Grandine.CheckpointSyncUrl https://sync-mainnet.beaconcha.in --Grandine.Features LogBlockProcessingTime,LogHttpRequests,DebugP2pMessages,WarnOnStateCacheSlotProcessing,WarnOnFailedServiceHealthChecks --Grandine.MetricsUpdateInterval 1 --Grandine.TelemetryMetricsUrl http://tempo:4317 --Grandine.TelemetryServiceName embedded-grandine-hoodi --Grandine.TelemetryLevel debug --Grandine.BackSync true --init-logrules Grandine.NethermindPlugin.*:debug --datadir /data/nethermind --JsonRpc.EngineHost 0.0.0.0 --JsonRpc.EnginePort 8551 --JsonRpc.JwtSecretFile /data/jwtsecret